x-rman-env: &rman-env
  # -- Stage of the app
  #    It should be one of: dev, prod
  MODE: dev

  # -- Set secure password. Should be differents
  MARIADB_PASSWORD: <secure_password>
  MARIADB_ROOT_PASSWORD: <secure_root_password>

  # -- It should be 128 hex characters
  #    It can be a SHA-512 hash. https://emn178.github.io/online-tools/sha512.html
  SECRET_KEY: 673d4b1d7deabe33d0037d3a39927ec3d56397a45f5eb9ac0512c75808c293f0d022e04adc5555cd3644d18cf79e9e9ebaea7e3a8e96744b0c49312a7f8af398

  # -- Don't need to modify these
  MARIADB_HOST: rman-mariadb
  COSMO_LOGGER: warn,error
  MARIADB_DATABASE: rman
  MARIADB_USER: rman_service

name: cosmito
services:
  base-image-builder:
    environment: *rman-env
    extends:
      file: docker/global.compose.yml
      service: _cosmo-build-image
  base-setup:
    environment: *rman-env
    extends:
      file: docker/global.compose.yml
      service: setup
  base-cleanup:
    environment: *rman-env
    extends:
      file: docker/global.compose.yml
      service: cleanup

  rman-mariadb:
    environment: *rman-env
    extends:
      file: docker/rman.compose.yml
      service: mariadb
  rman-service:
    environment: *rman-env
    extends:
      file: docker/rman.compose.yml
      service: service