services:
  rman-mariadb:
    image: mariadb:lts
    restart: always
    volumes:
      # - ./cache/rman/mysql:/var/lib/mysql:Z
      - ./services/rman/src/repos/mariadb/init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    env_file:
      - ./services/rman/.env.dev

  rman:
    build: .
    working_dir: /app/services/rman
    restart: always
    depends_on:
      - rman-mariadb
    volumes:
      - ./services/rman:/app/services/rman
      - ./packages/rman:/app/packages/rman
      - ./types/rman:/app/types/rman
    ports:
      - "50051:50051"
    command: yarn rman:dev
    env_file:
      - ./services/rman/.env.dev
