type Query {
	"""
	Fetches a _Resource_ and returns it
	"""
	fetchResource(id: ID!): Resource

	"""
	Fetches a _Authenticable Entity_ and returns it.

	If the entity logged has not permissions to fetch the secretHash,
	it will always be null.
	"""
	fetchAuthEntity(id: ID!): AuthEntity

	"""
	Assigns a permission an _Authenticable Entity_
	"""
	assignPermission(
		authEntityId: ID!
		resourceId: ID!
		permission: String!
	): Boolean
}

type Mutation {
	"""
	Creates a new _Resource_ and returns it
	"""
	createResource: Resource

	"""
	Archives a _Resource_ and returns it
	"""
	archiveResource(id: ID!): Resource

	"""
	Creates a new _Authenticable Entity_ and returns it
	"""
	createAuthEntity: AuthEntity
}

type Resource {
	id: ID!
	creatorId: ID!
	creationDate: String!
	modificationDate: String
	archiveDate: String
	archiverId: ID
}

type AuthEntity {
	id: ID!
	crid: ID!
	secretHash: String
}
