services:
  _cosmo-build-image:
    profiles:
      - setup
    container_name: Cosmo.ImageBuilder
    image: cosmo-general-image
    build: ..
    command: echo "cosmo-general-image builded"

  setup:
    profiles:
      - setup
    depends_on:
      - base-image-builder
      - base-cleanup
    image: cosmo-general-image
    working_dir: /app
    container_name: Cosmo.Setup
    volumes:
      - ../scripts:/app/scripts
      - ../services:/app/services
      - ../packages:/app/packages
      - ../types:/app/types
    command: sh -c "./scripts/setup"

  cleanup:
    profiles:
      - setup
      - cleanup
    depends_on:
      - base-image-builder
    image: cosmo-general-image
    working_dir: /app
    container_name: Cosmo.Cleaner
    volumes:
      - ../scripts:/app/scripts
      - ../services:/app/services
      - ../packages:/app/packages
      - ../types:/app/types
    command: sh -c "./scripts/cleanup"
