services:
    mariadb:
        profiles:
            - rman
            - services
        image: mariadb:lts
        container_name: ResourceManager.MariaDB
        restart: always
        volumes:
            # - ./cache/rman/mysql:/var/lib/mysql:Z
            - ../services/rman/misc/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3306:3306"

    service:
        profiles:
            - rman
            - services
        image: cosmo-general-image
        container_name: ResourceManager.Service
        working_dir: /app/services/rman
        restart: always
        depends_on:
            - base-build
            - rman-mariadb
        volumes:
            - ../services/rman:/app/services/rman
            - ../packages/rman:/app/packages/rman
            - ../types/rman:/app/types/rman
        ports:
            - "50051:50051"
        command: yarn rman:dev
