#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
COSMO_DIR=$(dirname $SCRIPT_DIR)

# -- Cleanup

. $COSMO_DIR/packages/core/scripts/cleanup
. $COSMO_DIR/services/rman/scripts/cleanup
