#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
COSMO_DIR=$(dirname $SCRIPT_DIR)

# -- Setup (the order matters)

# 1. Packages
. $COSMO_DIR/packages/core/scripts/setup

# 2. Services
. $COSMO_DIR/services/rman/scripts/setup