#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";

const RMAN_DIR = path.resolve(import.meta.dirname, "..");

/*
 * Summary:
 *  - Remove dist folder
 *  - Remove init.sql
 */

console.log("Cleaning up: Resource Manager");

function main() {
	const distPath = path.resolve(RMAN_DIR, "dist");
	fs.rmSync(distPath, { recursive: true, force: true });

	const initSqlPath = path.resolve(RMAN_DIR, "misc", "init.sql");
	fs.rmSync(initSqlPath, { force: true });
}

main();
